---
driver:
  name: vagrant
  provider: vmware_fusion

provisioner:
  name: chef_solo
  require_chef_omnibus: latest

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6
  - name: centos-7.1
  - name: macosx-1011
    driver:
      box_url: 'http://webdav.roblox.local/boxes/macosx_10.11.box'
      customize:
        cpus: 2
  - name: macosx-1012
    driver:
      box_url: 'http://webdav.roblox.local/boxes/macosx_10.12.box'
      customize:
        cpus: 2

suites:
  - name: appium_test
    run_list:
      - recipe[appium_test::android]
    attributes:
      java:
        jdk_version: 8
