---
driver:
  name: vagrant
  provider: vmware_fusion
  customize:
      memory: 2048

provisioner:
  name: chef_solo
#  require_chef_omnibus: 11.8.0

platforms:
  - name: macosx-10.10
    driver:
      box: macosx-10.10
  - name: ubuntu-14.04
  - name: centos-6.6
  - name: centos-7.0
    driver:
      network:
      - ["forwarded_port", {guest: 4444, host: 4444}]
      - ["forwarded_port", {guest: 5555, host: 5555}]
      - ["private_network", {ip: "192.168.33.70"}]

suites:
  - name: appium_test
    run_list:
      - recipe[appium_test::default]
    attributes:
      java:
        jdk_version: '7'
